/* Rollback - Process redirects to ZA/za_redirects-Categories-redirects.csv */

DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '380' and to_category_id = '416';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '651' and to_category_id = '362';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '650', to_category_id = '824', to_first_level_slug = 'vehicle-servicing';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '653' and to_category_id = '376';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '649' and to_category_id = '377';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '567' and to_category_id = '16';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '302' and to_category_id = '16';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '191' and to_category_id = '821';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '324', to_category_id = '824', to_first_level_slug = 'event-services';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '371', to_category_id = '824', to_first_level_slug = 'moving-storage';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '641', to_category_id = '824', to_first_level_slug = 'photography-video';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '640', to_category_id = '824', to_first_level_slug = 'legal-services';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '638', to_category_id = '824', to_first_level_slug = 'interior-design-decor';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '630', to_category_id = '824', to_first_level_slug = 'advertising-marketing';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '372', to_category_id = '824', to_first_level_slug = 'babysitter-domestic-help-gardening';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '642' and to_category_id = '824';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '643', to_category_id = '824', to_first_level_slug = 'moving-storage';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '206' and to_category_id = '824';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '370' and to_category_id = '824';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '631', to_category_id = '824', to_first_level_slug = 'event-services';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '322', to_category_id = '824', to_first_level_slug = 'computer';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '414', to_category_id = '824', to_first_level_slug = 'babysitter-domestic-help–gardening';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '632', to_category_id = '824', to_first_level_slug = 'babysitter-domestic-help–gardening';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '639', to_category_id = '824', to_first_level_slug = 'babysitter-domestic-help–gardening';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '634', to_category_id = '824', to_first_level_slug = 'event-services';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '635' and to_category_id = '824';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '199', to_category_id = '824', to_first_level_slug = 'health-beauty-fitness';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '636', to_category_id = '824', to_first_level_slug = 'health-beauty-fitness';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '637', to_category_id = '824', to_first_level_slug = 'services-cat-824';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '633', to_category_id = '824', to_first_level_slug = 'construction-renovation-repairs';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '198', to_category_id = '824', to_first_level_slug = 'construction-renovation-repairs';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '644', to_category_id = '824', to_first_level_slug = 'security-fencing';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '645', to_category_id = '824', to_first_level_slug = 'sewing-upholstery';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '646', to_category_id = '824', to_first_level_slug = 'classes';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '647', to_category_id = '824', to_first_level_slug = 'transport';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '648', to_category_id = '824', to_first_level_slug = 'travel-tourism-services';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '323', to_category_id = '824', to_first_level_slug = 'writing-editing-translating';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '207' and to_category_id = '824';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '186', to_category_id = '824', to_first_level_slug = 'classes';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '281', to_category_id = '824', to_first_level_slug = 'classes';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '279', to_category_id = '824', to_first_level_slug = 'classes';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '280', to_category_id = '824', to_first_level_slug = 'classes';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '278', to_category_id = '824', to_first_level_slug = 'classes';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '283', to_category_id = '824', to_first_level_slug = 'classes';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '605' and to_category_id = '603';
DELETE FROM olx_listing_redirect WHERE country_id = '193' AND from_category_id = '825' and to_category_id = '887';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '606', to_category_id = '401', to_first_level_slug = 'births';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '248', to_category_id = '381', to_first_level_slug = 'carpool';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '607', to_category_id = '381', to_first_level_slug = 'sports';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '608', to_category_id = '401', to_first_level_slug = 'deaths';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '609', to_category_id = '401', to_first_level_slug = 'festivals';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '413', to_category_id = '401', to_first_level_slug = 'lost-found';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '610', to_category_id = '381', to_first_level_slug = 'markets';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '611', to_category_id = '401', to_first_level_slug = 'marriages';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '244', to_category_id = '381', to_first_level_slug = 'concerts';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '612', to_category_id = '381', to_first_level_slug = 'volunteers';
DELETE FROM olx_listing_redirect WHERE country_id = '193', from_category_id = '382', to_category_id = '381', to_first_level_slug = 'volunteers';
