/* Process redirects to ZA/za_redirects-Categories-redirects.csv */

INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '380', '416');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '651', '362');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '650', '824', 'vehicle-servicing');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '653', '376');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '649', '377');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '567', '16');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '302', '16');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '191', '821');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '324', '824', 'event-services');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '371', '824', 'moving-storage');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '641', '824', 'photography-video');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '640', '824', 'legal-services');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '638', '824', 'interior-design-decor');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '630', '824', 'advertising-marketing');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '372', '824', 'babysitter-domestic-help-gardening');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '642', '824');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '643', '824', 'moving-storage');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '206', '824');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '370', '824');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '631', '824', 'event-services');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '322', '824', 'computer');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '414', '824', 'babysitter-domestic-help–gardening');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '632', '824', 'babysitter-domestic-help–gardening');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '639', '824', 'babysitter-domestic-help–gardening');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '634', '824', 'event-services');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '635', '824');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '199', '824', 'health-beauty-fitness');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '636', '824', 'health-beauty-fitness');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '637', '824', 'services-cat-824');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '633', '824', 'construction-renovation-repairs');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '198', '824', 'construction-renovation-repairs');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '644', '824', 'security-fencing');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '645', '824', 'sewing-upholstery');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '646', '824', 'classes');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '647', '824', 'transport');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '648', '824', 'travel-tourism-services');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '323', '824', 'writing-editing-translating');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '207', '824');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '186', '824', 'classes');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '281', '824', 'classes');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '279', '824', 'classes');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '280', '824', 'classes');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '278', '824', 'classes');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '283', '824', 'classes');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '605', '603');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id)  VALUES ('193', '825', '887');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '606', '401', 'births');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '248', '381', 'carpool');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '607', '381', 'sports');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '608', '401', 'deaths');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '609', '401', 'festivals');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '413', '401', 'lost-found');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '610', '381', 'markets');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '611', '401', 'marriages');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '244', '381', 'concerts');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '612', '381', 'volunteers');
INSERT INTO olx_listing_redirect (country_id, from_category_id, to_category_id, to_first_level_slug) VALUES ('193', '382', '381', 'volunteers');
